---
title: "Athletes Data Pairwise Comparison Survey (Cycle Tracking) - Recruitment & Survey Design and Participation Plan"
author: "Brad Stenger"
date: "2026-06-27"
---

### Scenario
Survey will test U.S. women college athletes attitudes and preferences for data sharing of their menstrual cycle tracking data with coaches and teammates. Results will inform work on developing privacy-enhanced tools for data sharing of athletes' data.

### Research Question
What are U.S. women college athletes attitudes and preferences for data sharing of their menstrual cycle tracking data with coaches and teammates for the purpose of success for both individual athlete and their team? 

### Survey Method
The survey will ask participants to choose between two vignette scenarios, expressing their preference for which scenario is "more appropriate" in terms of their privacy preferences. Vignettes are structured descriptive scenarios, each one phrased to include a randomized set of specific parameters that describe the research question context. The pairwise comparison survey methodology fits college athlete populations who require small, flexible time windows in order to participate. Survey vignettes use the contextual integrity framework (a method for describing information flows in privacy-relevant contexts) for scenarios and their combinations.

### Initial Questions before Survey
0. Must ask: Women student-athletes approach to menstruation and its affect on athletic performance?
    * slider 0-100 for how much attention they pay to their period related to their athletic performance
    * why that number?
    * information preferences checkboxes: birth control, period tracking app, period tracking wearable, period tracking journal, past pregnancy, political awareness
1. Question: Do we want to have participant demographics? (gender, location, revenue-nonrevenue, team-individual, freshman-upperclass, age, privacy-sensitivity)
    * If yes, which demographics?

### Survey Construction in Qualtrics
0. Survey will randomly pair combinations of information flows fo (determined by contextual integrity framework) and ask survey taker to judge which one is "more appropriate." The actual process in Qualtrics is to have a choose-from list with all of the vignette combinations where two items' choices are shown at random and then hide the rest of the choices from survey takers. 
1. Survey participants will be asked for 5 pairwise comparisons.
2. We can plan to give survey participants the opportunity to do more pairwise comparisons. 

### Simulation: Data and Analysis (so far)
```{r}
#| echo: true
#| eval: true
#| message: false
#| warning: false
library(jsonlite)
library(tidyr)
library(dplyr)

json <- '{
    "datatype": ["journal","app","wearable","birth control"],
    "sender": ["strength coach","data analyst","athletic trainer"],
    "tp": ["player status","team analysis","health concern"],
    "recipient": ["head coach","whole team","strength coach","athletic trainer"],
    "purpose": ["training","game planning","performance review"]
}'
ci <- jsonlite::fromJSON(json)
combinations <- expand.grid(ci$datatype,ci$sender,ci$tp,ci$recipient)
names(combinations) <- c("datatype","sender","tp","recipient")
set.seed(1)
pair_ones <- combinations[sample(nrow(combinations), 30, replace = TRUE), ]
pair_twos <- combinations[sample(nrow(combinations), 30, replace = TRUE), ]
df <- tibble(
  pair_one = pair_ones,
  pair_two = pair_twos
)
results <- df %>%
  rowwise() %>%
  mutate(winners = sample(list(pair_one, pair_two), size = 1)[[1]]) %>%
  ungroup()
results$winners
#.. format data to match Heis example

```

### Survey Process
1. Email invitation to survey from template
2. Use [Qualtrics Emailer](https://www.qualtrics.com/support/survey-platform/distributions-module/email-distribution/emails-overview/) for survey invitations, enables single submission per email invitation
3. Use [Qualtrics Authenticator](https://www.qualtrics.com/support/survey-platform/survey-module/survey-flow/advanced-elements/authenticator/authenticator-overview/) for survey participation, matches survey taker to contact list
4. Survey Instructions page, includes essential background information
5. Survey
    * user testing needed to judge correct number of pairwise comparison questions
    * Q: do we want to include one optional open-ended response after pairwise comparison questions? It seems like a missed opportunity if not included.
6. Qualtrics data export for analysis and participant payment (separate workflows)

### Analysis workflow
1. done in R Studio and Quarto environments
2. Facets win percentage from pairwise comparisons
3. Bayesian Hierarchical Analysis for Average Marginal Component Effects and Marginal Means, describes differences between facets
4. Elo Rankings, advanced prediction model derived from facets win percentage

### Payments workflow
1. contact information exported with Qualtrics survey results
2. electronic gift card payment automation with Amazon Incentives API and with Twilio Sendgrid Email API

### Paid-for Email List for Survey Panel
1. constraint: percentage results are only analysis that can be reported
    * constraint comes from contractual agreement between Student Athlete Insights consultancy and student-athlete participants in their mail list
    * pairwise comparison win percentage is one available metric given the constraint
    * Bayesian Hierarchical Analysis is also available. The survey is analogous to political strategy research comparing Candidate-A with a set of categorized descriptors to Candidate-B with a different set of categorized descriptors. Using pairwise comparison all Candidate combinations, those description will show measurable gain (or loss) in expected percentage. [Heis, Conjoint Analysis in R](https://www.andrewheiss.com/blog/2023/07/25/conjoint-bayesian-frequentist-guide/)
2. if no constraint
    * Elo rankings and odds-ratio analysis would be available for public presentation of results (still available for private analysis)
    * other sources for paid email list: CoachMePlus, Teamworks (no guarantee that either is willing to help)
3. **assessment:** easiest course of action
    * Q: is it realistic to expect a certain number of participants/dollar with pilot tests?
    * Q: can pilot tests with small numbers of athletes (< 5) indicate larger-scale participation levels in addition to finalizing wording for survey questions?
    * Q: what are the cost differences between single + large survey invitation sendouts vs. multiple + smaller survey invitation sendouts?

### Snowball Recruiting to Create Survey Panel from Scratch
1. seed: student-athletes who will offered opportunity to take the survey, and who will likely refer other student-athletes in their network to take survey
    * UVM, UVA athlete network (lower quality, lower cost)
    * seed from Student Athlete Insights network (higher quality, higher cost)
    * personal outreach for seed student-athletes from Athletes Data Community Newsletter mail list
2. create participant id + email invitation to survey for each seed (json + Python + Sendgrid)
    * may want to include identity verification using email address in order to prevent forwarding survey link
    * if forwarded links are caught as unverified, it might be worth the effort to verify the attempted survey taker as a U.S. student athlete
3. survey instructions and essential background (300-400 words) + survey + referrals (both survey and referral requests are in the same Qualtrics survey)
4. referral confirmation as student-athlete at U.S. college
    * if ok referral gets participant id => proceed with steps 2 and 3
    * checking referral is 100% necessary to 
5. payments
    * completed survey
    * referral completed survey
6. cutoff
    * number of participants
    * time window
    * money is spent
    * be sure to mention cutoff in email invitation to survey
    * make sure Qualtrics stays up to date, replace first page and say that survey has ended when cutoff has been reached
7. start over if more participants needed
    * evaluate seed participants
    * evaluate payment/incentive
    * check referral network for downstream effectiveness
8. analysis
    * no constraint
    * win percentage
    * Bayesian percentage changes from ACME and marginal mean
    * Elo ranking
9. **assessment:** highest potential number of participants/dollar, least certainty of reaching participation objectives
    * ownership of mail list that results, with availability for future, similar surveys

### 2-Panel Hybrid with both Paid + Snowball 
1. determine ratio of paid list to snowball recruiting
    * test with pilot experiments to gauge effectiveness of each approach
    * adaptive iterations based on small-scale survey releases (either paid list or snowball recruiting) will add cost and time
2. analysis
    * differs by recruitment method
    * separate but identical Qualtrics surveys to sandbox results according to recruitment method -- No Mixing
    * Elo not availables using Student Athlete Insights network, shows relative benefit of Elo ranking
3. **assessment:** balances cost and risk
    * assurance of reaching floor-level of survey response participation with Student Athlete Insights network mail list outreach
    * opportunity to learn while also obtaining survey responses by doing snowball recruiting
    * might be possible to stagger starting points, assess snowball recruiting and then use paid mail list as 